//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoLitvin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        public int DNI { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public int IDNacionalidad { get; set; }
        public int IDEstadoJudicial { get; set; }
    
        public virtual EstadosJudiciale EstadosJudiciale { get; set; }
        public virtual Nacionalidade Nacionalidade { get; set; }
    }
}
